services:
  freqtrade:
    # Development build using the latest freqtrade develop image
    image: freqtradeorg/freqtrade:develop
    restart: always
    container_name: freqtrade-dev
    ports:
      # Expose REST API for local access
      - "8080:8080"
    environment:
      # Telegram via env (optional) - prefer .env file or export in shell
      - FREQTRADE__TELEGRAM__ENABLED=${TELEGRAM_ENABLED:-false}
      - FREQTRADE__TELEGRAM__TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - FREQTRADE__TELEGRAM__CHAT_ID=${TELEGRAM_CHAT_ID:-}
      # REST basic auth via env (optional)
      - FREQTRADE__API_SERVER__USERNAME=${FREQTRADE_API_USERNAME:-YOUR_USERNAME}
      - FREQTRADE__API_SERVER__PASSWORD=${FREQTRADE_API_PASSWORD:-YOUR_PASSWORD}
    volumes:
      # Persist user data (strategies, configs, data)
      - ./user_data:/freqtrade/user_data
      # Persist logs separately for easier access
      - ./user_data/logs:/freqtrade/user_data/logs
      # Persist database files outside the container
      - ./user_data/db:/freqtrade/user_data/db
    command:
      - trade
      - --config
      - /freqtrade/user_data/config.json
      - --strategy
      - SampleStrategy
      - --dry-run
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests,sys; sys.exit(0) if requests.get('http://localhost:8080/api/v1/ping', timeout=2).ok else sys.exit(1)\""]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 20s

  reporter:
    image: freqtradeorg/freqtrade:develop
    container_name: freqtrade-reporter
    depends_on:
      freqtrade:
        condition: service_healthy
    restart: unless-stopped
    entrypoint: ["python", "/freqtrade/report.py"]
    environment:
      # Freqtrade REST target (use service DNS inside the compose network)
      - FREQTRADE_API_URL=http://freqtrade:8080/api/v1
      - FREQTRADE_API_USERNAME=${FREQTRADE_API_USERNAME:-YOUR_USERNAME}
      - FREQTRADE_API_PASSWORD=${FREQTRADE_API_PASSWORD:-YOUR_PASSWORD}
      # Telegram credentials (provided via .env or shell)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
      # Reporter behavior
      - REPORT_INTERVAL_SECONDS=${REPORT_INTERVAL_SECONDS:-1800}
      - TELEGRAM_SILENT=${TELEGRAM_SILENT:-true}
      - REPORT_INCLUDE_PAIRLIST=${REPORT_INCLUDE_PAIRLIST:-true}
      - REPORT_PAIRLIST_STYLE=${REPORT_PAIRLIST_STYLE:-columns}
      - REPORT_PAIRLIST_LIMIT=${REPORT_PAIRLIST_LIMIT:-30}
    volumes:
      - ./user_data:/freqtrade/user_data
      - ./report.py:/freqtrade/report.py:ro
